### ISSUE TITLE
Delay between slides decrease over time

### ISSUE THREAD

**Issue by haggen** [davidlpz/krakatoa#5]
I just noticed a bug; after 1 or 2 minutes with the page open the delay between the slides start to go crazy and the slides start to change really fast.

I'm willing to fix it but right now I don't have the time, so I just wanted to let you know.

Nice plugin by the way. ;)

**Comment by davidlpz** [comment]
Hi, Arthur. do you have the latest version of the plugin? It was supposed to be fixed by now :/

Thanks!

**Comment by haggen** [comment]
I guess so, I downloaded it at the end of December.

**Comment by davidlpz** [comment]
Yeah, that's the latest. I'll check it out, then.

**Comment by haggen** [comment]
Like I said I might look into it any day soon, since I'm using it in a client's site he already complained it's in the todo list. :P Then I can send a pull request.

**Comment by davidlpz** [comment]
I've been testing it but I doesn't seem to broke always. Do you have any more clues about when it happens? What settings are you using?
