### ISSUE TITLE
Function inside Krakatoa Slider

### ISSUE THREAD

**Issue by manlioma** [davidlpz/krakatoa#6]
Hi ! is it possible to create a function inside krakatoa ?

I need to add anotrìher jquery plugin for Fit to screen image in responsive website..
Do you know I can get it ?

thanx

**Comment by davidlpz** [comment]
¿Why don't you just set the .krakatoa element width to 100%? Like this:

$('.krakatoa').krakatoa( { width: 100%; } );

**Comment by manlioma** [comment]
Hi., my slider has width 100%, but the images inside are different, and I
need to align vertical. I use another plugin that do this, but doesn't work
with the images inside krakatoa.

So I thought there was some callback function...but I don't know ...if you
want to see, here's the link http://www.kickproduction.it/dna/
thank you very much !

2014-02-10 20:43 GMT+01:00 David López notifications@github.com:

> ¿Why don't you just set the .krakatoa element width to 100%? Like this:
> 
> $('.krakatoa').krakatoa( { width: 100%; } );
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/davidlpz/krakatoa/issues/6#issuecomment-34673463
> .

## 

Manlio Massimetti
+39 339 28 26 912
mmanlio@gmail.com

**Comment by davidlpz** [comment]
I've added a callback function to execute when everything is set. Try this:

$('.krakatoa').krakatoa( { function: 'functionName' });

Be sure to change the 'direction' option, because you have an older version and now works with 1 or -1, not 'right' and 'left'.

**Comment by manlioma** [comment]
thank you very much ! I'll let you know !
great works ;)

2014-02-10 22:00 GMT+01:00 David López notifications@github.com:

> I've added a callback function to execute when everything is set. Try this:
> 
> $('.krakatoa').krakatoa( { function: 'functionName' });
> 
> Be sure to change the 'direction' option, because you have an older
> version and now works with 1 or -1, not 'right' and 'left'.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/davidlpz/krakatoa/issues/6#issuecomment-34681742
> .

## 

Manlio Massimetti
+39 339 28 26 912
mmanlio@gmail.com

**Comment by manlioma** [comment]
Hi David, could you check this code ? I need to add a perfect scroll bar after krakatoa is loaded

```
    $('#calendoscopio').krakatoa( { width: '100%', height: '800px', autoplay: true, buttons: true, gutter: 20, loop: true, items: 4, // 
      direction: 1, // Movement of the slider.
      delay: 3500, // Delay of the next movement
      duration: 800,
      callback: function() {
            $('.concerti').perfectScrollbar();
        } });
```

**Comment by davidlpz** [comment]
In your scripts.js file, you have $('.concerti').perfectScrollbar(); two times, one before the loading and another one after it. Maybe is that it? In the Neutral Milk Hotel concert places I can see the scrollbar.

**Comment by manlioma** [comment]
yes I see the scrollbar but doesen't work, in script.js I need it for
another page

2014-02-18 15:42 GMT+01:00 David López notifications@github.com:

> In your scripts.js file, you have $('.concerti').perfectScrollbar(); two
> times, one before the loading and another one after it. Maybe is that it?
> In the Neutral Milk Hotel concert places I can see the scrollbar.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/davidlpz/krakatoa/issues/6#issuecomment-35390009
> .

## 

Manlio Massimetti
+39 339 28 26 912
mmanlio@gmail.com

**Comment by davidlpz** [comment]
Which one is the other page?

**Comment by manlioma** [comment]
wors here http://www.kickproduction.it/dna/calendario/
and here http://www.kickproduction.it/dna/artisti/neutral-milk-hotel/

2014-02-18 16:09 GMT+01:00 David López notifications@github.com:

> Which one is the other page?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/davidlpz/krakatoa/issues/6#issuecomment-35393125
> .

## 

Manlio Massimetti
+39 339 28 26 912
mmanlio@gmail.com

**Comment by davidlpz** [comment]
Try this instead of the first $('.concerti').perfectScrollbar();

if ($('.page-template-page-calendario-php').length>0 || 
    $('.single-post').length>0) {
    $('.concerti').perfectScrollbar();
}

**Comment by manlioma** [comment]
I try to callback some scripts that has to work inside krakatoa slider...
could you help me ? thank you very much

with this script callback functions doesn't works:

$('#calendoscopio').krakatoa( { width: '100%', height: '800px', autoplay:
false, buttons: true, gutter: 20, loop: true, items: 4, //
  direction: 1, // Movement of the slider.
  delay: 3500, // Delay of the next movement
  duration: 800,
  callback: function() {
$('#calendoscopio .concerti').perfectScrollbar();
$('.iconf').click(function() {
$(this).next().next().slideToggle('slow');
return false;
});
    } });
});

2014-02-18 16:38 GMT+01:00 David López notifications@github.com:

> Try this instead the first $('.concerti').perfectScrollbar();
> 
> if ($('.page-template-page-calendario-php').length>0 ||
> $('.single-post').length>0) {
> $('.concerti').perfectScrollbar();
> }
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/davidlpz/krakatoa/issues/6#issuecomment-35396138
> .

## 

Manlio Massimetti
+39 339 28 26 912
mmanlio@gmail.com

**Comment by davidlpz** [comment]
Checking your scripts.js file, I can see that you have the following code two times.

 $('.iconf').click(function() {
        $(this).next().next().slideToggle('slow');
        return false;
    }); 

Try deleting the one outside the callback.

**Comment by manlioma** [comment]
Yes, but I need it inside and outside krakatoa, Now I changed the class
inside krakatoa, but doesn't..

I just need to load some script inside krakatoa, after loaded

2014-03-04 16:47 GMT+01:00 David López notifications@github.com:

> Checking your scripts.js file, I can see that you have the following code
> two times.
> 
> $('.iconf').click(function() {
> $(this).next().next().slideToggle('slow');
> return false;
> });
> 
> Try deleting the one outside the callback.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/davidlpz/krakatoa/issues/6#issuecomment-36638189
> .

## 

Manlio Massimetti
+39 339 28 26 912
mmanlio@gmail.com

**Comment by davidlpz** [comment]
Why? I only see the iconf items inside the <div class="calendoscopio"> and you can do that only with the callback. The class name change doens't work, you're still attaching the event twice. "wow" before loaded and "iconf" after loaded.

I see that here works:
http://www.kickproduction.it/dna/calendario/
http://www.kickproduction.it/dna/artisti/neutral-milk-hotel/

So there's must be something with the home.

**Comment by manlioma** [comment]
Ok, I appreciate your help... but sorry I don't understand..
my javascript is the same in home, and in the other page... Now, in
homepage i added Krakatoa slider, inside krakatoa i need to replace the
same script that I have in other page. Inside krakatoa doesn't works,
outside krakatoa works...

whit this scenario I have 2 solutions:
1 - able to operate the javascript inside krakatoa slider
2 - change the slider and try another slider

tell me if i wrong something,
thank you very very much!!

2014-03-04 17:43 GMT+01:00 David López notifications@github.com:

> Why? I only see the iconf items inside the
> and you can do that only with the callback. The class name change doens't
> work, you're still attaching the event twice. "wow" before loaded and
> "iconf" after loaded.
> 
> I see that here works:
> http://www.kickproduction.it/dna/calendario/
> http://www.kickproduction.it/dna/artisti/neutral-milk-hotel/
> 
> So there's must be something with the home.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/davidlpz/krakatoa/issues/6#issuecomment-36645440
> .

## 

Manlio Massimetti
+39 339 28 26 912
mmanlio@gmail.com
