### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by yhwhdesign** [davidlpz/krakatoa#8]
Can I do the following with this.
- have thmbnails as navigation
- add arrows to the thumbnail navigation
- allow a 'big' active image of the thumbnail that is selected
- show previous and next images on each side of the active big image
- add arrows for single image navigation on big images
- responsive
- touch enabled
- add icons for full screen and or for opening / closing of social icons and captions

**Comment by davidlpz** [comment]
Sorry, but the answer to most of your requests is no.

Maybe this is more what you need: http://kenwheeler.github.io/slick/
